project:
  type: website
  output-dir: docs


website:
  title: "winteraka22"
  search: true
  navbar:
    left:
      - href: ./day1.qmd
      - href: ./day2.qmd
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    code-tools: true
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

execute: 
  cache: true
  warning: false
