project:
  type: website
  output-dir: docs


website:
  title: "winteraka22"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

execute: 
  warning: false
