project:
  type: website
  output-dir: docs


website:
  title: "winteraka22"
  search: true
  navbar:
    left:
      - href: ./day1.qmd
      - href: ./day2.qmd
      - href: ./day3.qmd
      - text: Beispiele
        menu: 
        - ./boardgames.qmd
        - ./bechdel.qmd
        - ./chocolate.qmd
        - ./unfall.qmd
      - href: index.qmd
        text: Home

format:
  html:
    code-tools: true
    code-link: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute: 
  cache: true
  warning: false
